# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/mongodb/go"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/mssql/go"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "pip"
    directory: "/mysql/python-mysql-connector-python"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/mysql/python-PyMySQL"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/nats/go"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/oracle/go"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/oracle/python"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/postgresql/go"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/rabbitmq/go"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/rabbitmq/php"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/redis/go"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/redis/php"
    schedule:
      interval: "daily"