name: Go Testing

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "5 1 * * *"

jobs:
  mongodb:
    name: MongoDB
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: mongodb/go

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version:  '1.19'

      - name: Run go build .
        run: go build
